import { Post } from "@/app/types/posts"

export const dummyPosts: Post[] = [
    {
        title: "Scaling Distributed Systems",
        content: "An in-depth guide on how to efficiently scale distributed systems to handle millions of requests.",
        companyId: "1",
        companyName: "TechPioneers Inc.",
        userId: "101",
        createdAt: new Date("2024-12-01T10:00:00Z"),
        updatedAt: new Date("2024-12-02T12:00:00Z"),
        mediaUrl: "https://example.com/images/scaling.jpg",
    },
    {
        title: "Future of AI Agents",
        content: "Exploring the impact of AI agents on the next decade of innovation and human productivity.",
        companyId: "2",
        companyName: "AIVisionary Co.",
        userId: "102",
        createdAt: new Date("2024-11-28T08:30:00Z"),
        updatedAt: new Date("2024-11-29T09:00:00Z"),
        mediaUrl: "https://example.com/images/ai-future.jpg",
    },
    {
        title: "Kubernetes Best Practices",
        content: "A practical guide to optimize Kubernetes deployments and ensure smooth CI/CD workflows.",
        companyId: "3",
        companyName: "CloudNexus",
        userId: "103",
        createdAt: new Date("2024-12-05T14:15:00Z"),
        updatedAt: new Date("2024-12-06T16:00:00Z"),
        mediaUrl: "https://example.com/images/kubernetes.jpg",
    },
    {
        title: "Building Resilient Microservices",
        content: "Tips and tools to build microservices that can withstand failures and recover gracefully.",
        companyId: "4",
        companyName: "ResilientTech",
        userId: "104",
        createdAt: new Date("2024-11-30T11:20:00Z"),
        updatedAt: new Date("2024-12-01T13:50:00Z"),
        mediaUrl: "https://example.com/images/microservices.jpg",
    },
    {
        title: "Empowering Remote Teams",
        content: "How to foster collaboration and productivity in a remote-first work environment.",
        companyId: "5",
        companyName: "TeamEmpower",
        userId: "105",
        createdAt: new Date("2024-12-03T09:00:00Z"),
        updatedAt: new Date("2024-12-04T10:30:00Z"),
        mediaUrl: "https://example.com/images/remote-teams.jpg",
    },
];
